export const friendlyNames = {
    falcon: 'Captain Falcon',
    wiifit: 'Wii Fit Trainer',
    gandw: 'Game & Watch',
    duckhunt: 'Duck Hunt',
    rosalina: 'Rosalina & Luma',
    littlemac: 'Little Mac',
    drmario: 'Dr Mario',
    iceclimbers: 'Ice Climbers',
    banjo: 'Banjo & Kazooie',
    bowserjr: 'Bowser Jr',
    darkpit: 'Dark Pit',
    kingdedede: 'King Dedede',
    metaknight: 'Meta Knight',
    zss: 'Zero Suit Samus',
    darksamus: 'Dark Samus',
    donkeykong: 'Donkey Kong',
    diddykong: 'Diddy Kong',
    krool: 'King K. Rool',
    plant: 'Piranha Plant',
    toonlink: 'Toon Link',
    younglink: 'Young Link',
    megaman: 'Mega Man',
    minmin: 'Min Min',
}
