export const seriesNames = [
    { name: 'animalcrossing', characters: ['villager', 'isabelle'] },
    { name: 'donkeykong', characters: ['donkeykong', 'diddykong', 'krool'] },
    { name: 'finalfantasy', characters: ['cloud', 'sephiroth'] },
    { name: 'kirby', characters: ['kirby', 'kingdedede', 'metaknight'] },
    {
        name: 'mario',
        characters: ['mario', 'peach', 'plant', 'daisy', 'yoshi', 'luigi'],
    },
    { name: 'metroid', characters: ['samus', 'zss', 'ridley', 'darksamus'] },
    { name: 'mother', characters: ['ness', 'lucas'] },
    { name: 'palutena', characters: ['pit', 'darkpit', 'palutena'] },
    {
        name: 'pokemon',
        characters: [
            'pichu',
            'pikachu',
            'jigglypuff',
            'charizard',
            'ivysaur',
            'squirtle',
            'mewtwo',
            'incineroar',
            'greninja',
            'lucario',
        ],
    },
    { name: 'starfox', characters: ['fox', 'falco', 'wolf'] },
    { name: 'streetfighter', characters: ['ken', 'ryu'] },
    { name: 'xenoblade', characters: ['shulk', 'mythra', 'pyra'] },
    {
        name: 'zelda',
        characters: ['ganondorf', 'link', 'toonlink', 'younglink', 'zelda', 'sheik'],
    },
]
